[project]
name = 'BTC-Native-DeFi-Lending-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.BTC-Native-DeFi-Lending-Protocol]
path = 'contracts/BTC-Native-DeFi-Lending-Protocol.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
